import * as fs from "fs";
import * as path from "path";

const SKILLS_DIR = path.join(__dirname, "..", "data", "skills");

interface RawSkill {
    name: string;
    description: string;
    allowedTools: string;
    version: string;
    license: string;
    author: string;
    category: string;
    categorySlug: string;
    tags: string[];
    content: string;
}

function parseFrontmatter(raw: string): Record<string, string> {
    const match = raw.match(/^---\n([\s\S]*?)\n---/);
    if (!match) return {};
    const frontmatter: Record<string, string> = {};
    for (const line of match[1].split("\n")) {
        const idx = line.indexOf(":");
        if (idx === -1) continue;
        const key = line.slice(0, idx).trim();
        let value = line.slice(idx + 1).trim();
        // Remove surrounding quotes
        if (value.startsWith('"') && value.endsWith('"')) {
            value = value.slice(1, -1);
        }
        frontmatter[key] = value;
    }
    return frontmatter;
}

function parseCategoryReadme(categoryPath: string): { description: string; tags: string[] } {
    const readmePath = path.join(categoryPath, "README.md");
    if (!fs.existsSync(readmePath)) return { description: "", tags: [] };
    const content = fs.readFileSync(readmePath, "utf-8");

    // First paragraph after the heading: "# Title\n\nDescription line"
    const lines = content.split("\n");
    let description = "";
    for (let i = 0; i < lines.length; i++) {
        if (lines[i].startsWith("# ") && i + 2 < lines.length) {
            description = lines[i + 2].trim();
            break;
        }
    }

    // Tags section: "## Tags\n\n`tag1`, `tag2`, ..."
    const tagsIdx = lines.findIndex((l) => l.trim() === "## Tags");
    let tags: string[] = [];
    if (tagsIdx !== -1 && tagsIdx + 2 < lines.length) {
        const tagsRaw = lines[tagsIdx + 2].trim();
        tags = tagsRaw
            .split(/[`,]+/)
            .map((t) => t.trim())
            .filter(Boolean);
    }

    return { description, tags };
}

function getCategoryName(slug: string): string {
    return slug
        .split("-")
        .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
        .join(" ");
}

function getSkillContent(skillPath: string): string {
    const raw = fs.readFileSync(skillPath, "utf-8");
    // Remove frontmatter
    const match = raw.match(/^---\n[\s\S]*?\n---\n([\s\S]*)$/);
    return match ? match[1].trim() : raw.trim();
}

function main() {
    const categories = fs
        .readdirSync(SKILLS_DIR)
        .filter((f) => {
            const p = path.join(SKILLS_DIR, f);
            return fs.statSync(p).isDirectory();
        })
        .sort();

    const allSkills: RawSkill[] = [];
    const categoryData: { slug: string; name: string; description: string; tags: string[] }[] = [];

    for (const catSlug of categories) {
        const catPath = path.join(SKILLS_DIR, catSlug);
        const { description: catDesc, tags: catTags } = parseCategoryReadme(catPath);
        const catName = getCategoryName(catSlug);

        categoryData.push({ slug: catSlug, name: catName, description: catDesc, tags: catTags });

        const skillDirs = fs
            .readdirSync(catPath)
            .filter((f) => {
                const p = path.join(catPath, f);
                return fs.statSync(p).isDirectory();
            })
            .sort();

        for (const skillDir of skillDirs) {
            const skillMdPath = path.join(catPath, skillDir, "SKILL.md");
            if (!fs.existsSync(skillMdPath)) continue;

            const raw = fs.readFileSync(skillMdPath, "utf-8");
            const fm = parseFrontmatter(raw);
            const content = getSkillContent(skillMdPath);

            allSkills.push({
                name: fm.name || skillDir,
                description: (fm.description || "").replace(/\n/g, " ").trim(),
                allowedTools: fm["allowed-tools"] || "",
                version: fm.version || "1.0.0",
                license: fm.license || "MIT",
                author: fm.author || "",
                category: catName,
                categorySlug: catSlug,
                tags: catTags,
                content,
            });
        }
    }

    // Generate TypeScript
    const ts = `// Auto-generated by scripts/generate-skills.ts — do not edit manually

export interface Skill {
    id: string;
    name: string;
    slug: string;
    description: string;
    category: string;
    categorySlug: string;
    allowedTools: string;
    version: string;
    license: string;
    author: string;
    tags: string[];
    content: string;
}

export interface SkillCategory {
    slug: string;
    name: string;
    description: string;
    tags: string[];
}

export const skillCategories: SkillCategory[] = ${JSON.stringify(categoryData, null, 4)};

export const skills: Skill[] = ${JSON.stringify(
        allSkills.map((s, i) => ({
            id: String(i + 1),
            name: s.name,
            slug: s.name,
            description: s.description,
            category: s.category,
            categorySlug: s.categorySlug,
            allowedTools: s.allowedTools,
            version: s.version,
            license: s.license,
            author: s.author,
            tags: s.tags,
            content: s.content,
        })),
        null,
        4
    )};

export function getSkillBySlug(slug: string) {
    return skills.find((s) => s.slug === slug);
}

export function getSkillsByCategory(categorySlug: string) {
    if (categorySlug === "all") return skills;
    return skills.filter((s) => s.categorySlug === categorySlug);
}

export function getSkillsByCategoryName(categoryName: string) {
    return skills.filter((s) => s.category === categoryName);
}
`;

    const outPath = path.join(__dirname, "..", "data", "skills.ts");
    fs.writeFileSync(outPath, ts, "utf-8");
    console.log(`Generated ${allSkills.length} skills across ${categories.length} categories → data/skills.ts`);
}

main();
